modLoader = "javafml"
loaderVersion = "[1,)"
#issueTrackerURL = ""
license = "Insert License Here"

[[mods]]
modId = "immersive_wt"
version = "${version}"
displayName = "Immersive War Thunder"
authors = "WolfGenerals"
description = '''
'''
#logoFile = "assets/immersive_wt/icon.png"
[[mixins]]
config = "immersive_wt.mixins.json"
[[mixins]]
config = "immersive_wt-common.mixins.json"

[[dependencies.immersive_wt]]
modId = "neoforge"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_wt]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.immersive_wt]]
modId = "immersive_aircraft"
mandatory = true
versionRange = "[1.0.0,)"
ordering = "NONE"
side = "BOTH"